### GET request to example server
PUT http://localhost:4000/patients/5c272335-9b1c-4ab2-b6f4-4d206c835a03
Content-Type: application/json

{
  "name": "Tharun Pirangi",
  "email": "tharun.pirangi@gmail.com",
  "address": "i don't know it",
  "dateOfBirth": "2000-01-01"
}
###